// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var then = (function(p, cont) {
  Promise.resolve(p).then(cont)
});

var _catch = (function(p, cont) {
  Promise.resolve(p).catch(cont)
});

function $$catch(promise, callback) {
  return _catch(promise, (function (err) {
                return callback(Caml_js_exceptions.internalToOCamlException(err));
              }));
}

export {
  $$catch ,
  then ,
}
/* No side effect */
